version: '2'

services:
    mariadb:
        image: mariadb:10.4.5
        container_name: mariadb
        environment:
          MYSQL_ROOT_PASSWORD: passme
          MYSQL_DATABASE: mydb
          MYSQL_USER: user
          MYSQL_PASSWORD: passme
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - code-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mariadb:db
        ports:
            - 8000:80
        environment:
          MYSQL_ROOT_PASSWORD: passme
        networks:
            - code-network
    web:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./Fragebogen:/Fragebogen
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        networks:
            - code-network
    php:
        image: php:7-fpm
        volumes:
            - ./Fragebogen:/Fragebogen
        networks:
            - code-network
networks:
    code-network:
        driver: bridge
